#theme: jekyll-theme-slate

remote_theme: hydecorp/hydejack
# the rest from the config file as

plugins:
  - jekyll-remote-theme

title: brdn.io
description: A blog to capture projects and ramblings


# Add links to the sidebar.
menu:
  - title:             Example
    url:               /example/
  - title:             Documentation
    url:               /docs/
  - title:             About
    url:               /about/
