title: brdn.io
description: A blog to capture projects and ramblings

remote_theme: hydecorp/hydejack

plugins:
  - jekyll-remote-theme
  - jekyll-paginate

# Add links to the sidebar.
menu:
  - title:             About
    url:               /about
  - title:             Blog
    url:               /blog/



paginate:      10
paginate_path: /blog/:num/ #!!
